export enum ErrorCode {
  ROOM_NOT_FOUND = "ROOM_NOT_FOUND",
  ROOM_FULL = "ROOM_FULL",
  ROOM_ALREADY_STARTED = "ROOM_ALREADY_STARTED",
  PLAYER_NOT_IN_ROOM = "PLAYER_NOT_IN_ROOM",
  MATCH_NOT_FOUND = "MATCH_NOT_FOUND",
  MATCH_ALREADY_STARTED = "MATCH_ALREADY_STARTED",
  ROUND_NOT_ACTIVE = "ROUND_NOT_ACTIVE",
  ALREADY_ANSWERED = "ALREADY_ANSWERED",
  ANSWER_SUBMISSION_CLOSED = "ANSWER_SUBMISSION_CLOSED",
  NOT_ROOM_HOST = "NOT_ROOM_HOST",
  NOT_ENOUGH_PLAYERS = "NOT_ENOUGH_PLAYERS",
  UNAUTHORIZED = "UNAUTHORIZED",
  INVALID_TOKEN = "INVALID_TOKEN",
  RATE_LIMITED = "RATE_LIMITED",
  INTERNAL_ERROR = "INTERNAL_ERROR",
  INVALID_ROOM_TYPE = "INVALID_ROOM_TYPE",
  // Drop-in spectating baseline (PR): emitted when a user that is not
  // a registered player in the match tries to submit an answer.
  // Server-side gate in MatchHandler.handleSubmitAnswer.
  SPECTATOR_CANNOT_ANSWER = "SPECTATOR_CANNOT_ANSWER",
}
